name: build-ublue
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
  schedule:
    - cron: '20 20 * * *'  # 8:20pm everyday
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
env:
    IMAGE_BASE_NAME: main
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-22.04
    container:
      image: fedora:${{ matrix.image_version }} #quay.io/fedora-ostree-desktops/buildroot
      # Privilleged
      options: --privileged --platform linux/${{ matrix.arch }}
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image_name: [silverblue, kinoite, sericea, vauxite, base]
        arch: [x86_64, aarch64]
        # Change this to the branch's version!
        version: [39]
        image_version: [latest]
    steps: 
      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          dnf -y upgrade && dnf -y install buildah dbus-daemon file flatpak git-core jq just lorax ostree podman python3-pyyaml rpm-ostree selinux-policy-targeted skopeo tar zstd && dnf clean all

      - name: Compose image
        run: |
          just compose-image ${{ matrix.image_name }}
    
      - name: Import image
        run: |
          cat fedora-${{ matrix.image_name }}.ociarchive | podman import - fedora-ostree-desktop-${{ matrix.image_name}}:latest-${{ matrix.version }}-${{ matrix.arch }}

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        #if: github.event_name != 'pull_request'
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          image: fedora-ostree-desktop-${{ matrix.image_name}}
          tags: latest-${{ matrix.version }}-${{ matrix.arch }}
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
